namespace RuneHighlighter;

public static class RewardCatalog
{
    
    
    public static readonly (string Property, string Name)[] Items =
    {
        ("Reward__10x_Divine_Orb", "10x Divine Orb"),
        ("Reward__2x_Arcanist_s_Etcher", "2x Arcanist's Etcher"),
        ("Reward__2x_Armourer_s_Scrap", "2x Armourer's Scrap"),
        ("Reward__2x_Artificer_s_Orb", "2x Artificer's Orb"),
        ("Reward__2x_Blacksmith_s_Whetstone", "2x Blacksmith's Whetstone"),
        ("Reward__2x_Chaos_Orb", "2x Chaos Orb"),
        ("Reward__2x_Divine_Orb", "2x Divine Orb"),
        ("Reward__2x_Exalted_Orb", "2x Exalted Orb"),
        ("Reward__2x_Gemcutter_s_Prism", "2x Gemcutter's Prism"),
        ("Reward__2x_Glassblower_s_Bauble", "2x Glassblower's Bauble"),
        ("Reward__2x_Orb_of_Annulment", "2x Orb of Annulment"),
        ("Reward__2x_Orb_of_Augmentation", "2x Orb of Augmentation"),
        ("Reward__2x_Orb_of_Chance", "2x Orb of Chance"),
        ("Reward__2x_Orb_of_Transmutation", "2x Orb of Transmutation"),
        ("Reward__2x_Regal_Orb", "2x Regal Orb"),
        ("Reward__2x_Runic_Alloy", "2x Runic Alloy"),
        ("Reward__3x_Artificer_s_Orb", "3x Artificer's Orb"),
        ("Reward__3x_Chaos_Orb", "3x Chaos Orb"),
        ("Reward__3x_Divine_Orb", "3x Divine Orb"),
        ("Reward__3x_Exalted_Orb", "3x Exalted Orb"),
        ("Reward__3x_Gemcutter_s_Prism", "3x Gemcutter's Prism"),
        ("Reward__3x_Glassblower_s_Bauble", "3x Glassblower's Bauble"),
        ("Reward__3x_Greater_Chaos_Orb", "3x Greater Chaos Orb"),
        ("Reward__3x_Greater_Exalted_Orb", "3x Greater Exalted Orb"),
        ("Reward__3x_Greater_Orb_of_Augmentation", "3x Greater Orb of Augmentation"),
        ("Reward__3x_Greater_Orb_of_Transmutation", "3x Greater Orb of Transmutation"),
        ("Reward__3x_Greater_Regal_Orb", "3x Greater Regal Orb"),
        ("Reward__3x_Orb_of_Alchemy", "3x Orb of Alchemy"),
        ("Reward__3x_Orb_of_Annulment", "3x Orb of Annulment"),
        ("Reward__3x_Orb_of_Chance", "3x Orb of Chance"),
        ("Reward__3x_Perfect_Chaos_Orb", "3x Perfect Chaos Orb"),
        ("Reward__3x_Perfect_Exalted_Orb", "3x Perfect Exalted Orb"),
        ("Reward__3x_Perfect_Orb_of_Augmentation", "3x Perfect Orb of Augmentation"),
        ("Reward__3x_Perfect_Orb_of_Transmutation", "3x Perfect Orb of Transmutation"),
        ("Reward__3x_Perfect_Regal_Orb", "3x Perfect Regal Orb"),
        ("Reward__3x_Regal_Orb", "3x Regal Orb"),
        ("Reward__4x_Arcanist_s_Etcher", "4x Arcanist's Etcher"),
        ("Reward__4x_Armourer_s_Scrap", "4x Armourer's Scrap"),
        ("Reward__4x_Blacksmith_s_Whetstone", "4x Blacksmith's Whetstone"),
        ("Reward__5x_Random_Currency", "5x Random Currency"),
        ("Reward__6x_Arcanist_s_Etcher", "6x Arcanist's Etcher"),
        ("Reward__6x_Armourer_s_Scrap", "6x Armourer's Scrap"),
        ("Reward__6x_Blacksmith_s_Whetstone", "6x Blacksmith's Whetstone"),
        ("Reward__1x_Adaptive_Alloy", "1x Adaptive Alloy"),
        ("Reward__1x_Adept_Rune", "1x Adept Rune"),
        ("Reward__1x_Aldur_s_Legacy", "1x Aldur's Legacy"),
        ("Reward__1x_Aldur_s_Saga", "1x Aldur's Saga"),
        ("Reward__1x_Ancient_Rune_of_Animosity", "1x Ancient Rune of Animosity"),
        ("Reward__1x_Ancient_Rune_of_Control", "1x Ancient Rune of Control"),
        ("Reward__1x_Ancient_Rune_of_Decay", "1x Ancient Rune of Decay"),
        ("Reward__1x_Ancient_Rune_of_Detonation", "1x Ancient Rune of Detonation"),
        ("Reward__1x_Ancient_Rune_of_Discovery", "1x Ancient Rune of Discovery"),
        ("Reward__1x_Ancient_Rune_of_Dueling", "1x Ancient Rune of Dueling"),
        ("Reward__1x_Ancient_Rune_of_Prowess", "1x Ancient Rune of Prowess"),
        ("Reward__1x_Ancient_Rune_of_Retaliation", "1x Ancient Rune of Retaliation"),
        ("Reward__1x_Ancient_Rune_of_Shattering", "1x Ancient Rune of Shattering"),
        ("Reward__1x_Ancient_Rune_of_Splinters", "1x Ancient Rune of Splinters"),
        ("Reward__1x_Ancient_Rune_of_the_Horde", "1x Ancient Rune of the Horde"),
        ("Reward__1x_Ancient_Rune_of_the_Titan", "1x Ancient Rune of the Titan"),
        ("Reward__1x_Ancient_Rune_of_Witchcraft", "1x Ancient Rune of Witchcraft"),
        ("Reward__Skill_Animus_Exchange", "Skill: Animus Exchange"),
        ("Reward__Skill_Animus_Splinters", "Skill: Animus Splinters"),
        ("Reward__1x_Artificer_s_Orb", "1x Artificer's Orb"),
        ("Reward__1x_Astrid_s_Creativity", "1x Astrid's Creativity"),
        ("Reward__1x_Betrayal_of_Aldur", "1x Betrayal of Aldur"),
        ("Reward__Skill_Bitter_Dead", "Skill: Bitter Dead"),
        ("Reward__1x_Blazing_Flux", "1x Blazing Flux"),
        ("Reward__1x_Body_Rune", "1x Body Rune"),
        ("Reward__1x_Breath_of_Aldur", "1x Breath of Aldur"),
        ("Reward__1x_Cadigan_s_Epiphany", "1x Cadigan's Epiphany"),
        ("Reward__1x_Celestial_Alloy", "1x Celestial Alloy"),
        ("Reward__1x_Chaos_Orb", "1x Chaos Orb"),
        ("Reward__1x_Charging_Rune", "1x Charging Rune"),
        ("Reward__1x_Chilling_Flux", "1x Chilling Flux"),
        ("Reward__Support_Concussive_Runes", "Support: Concussive Runes"),
        ("Reward__Skill_Conductive_Runes", "Skill: Conductive Runes"),
        ("Reward__1x_Countess_Seske_s_Rune_of_Archery", "1x Countess Seske's Rune of Archery"),
        ("Reward__1x_Courtesan_Mannan_s_Rune_of_Cruelty", "1x Courtesan Mannan's Rune of Cruelty"),
        ("Reward__1x_Crackling_Flux", "1x Crackling Flux"),
        ("Reward__1x_Craiceann_s_Rune_of_Recovery", "1x Craiceann's Rune of Recovery"),
        ("Reward__1x_Craiceann_s_Rune_of_Warding", "1x Craiceann's Rune of Warding"),
        ("Reward__1x_Cyclonic_Alloy", "1x Cyclonic Alloy"),
        ("Reward__1x_Desert_Rune", "1x Desert Rune"),
        ("Reward__Skill_Detonate_Living", "Skill: Detonate Living"),
        ("Reward__1x_Divine_Orb", "1x Divine Orb"),
        ("Reward__Skill_Eternal_March", "Skill: Eternal March"),
        ("Reward__1x_Exalted_Orb", "1x Exalted Orb"),
        ("Reward__1x_Expansive_Alloy", "1x Expansive Alloy"),
        ("Reward__Skill_Explosive_Transmutation", "Skill: Explosive Transmutation"),
        ("Reward__1x_Farrul_s_Rune_of_Grace", "1x Farrul's Rune of Grace"),
        ("Reward__1x_Farrul_s_Rune_of_the_Chase", "1x Farrul's Rune of the Chase"),
        ("Reward__1x_Farrul_s_Rune_of_the_Hunt", "1x Farrul's Rune of the Hunt"),
        ("Reward__1x_Fenumus_Rune_of_Agony", "1x Fenumus' Rune of Agony"),
        ("Reward__1x_Fenumus_Rune_of_Draining", "1x Fenumus' Rune of Draining"),
        ("Reward__1x_Fenumus_Rune_of_Spinning", "1x Fenumus' Rune of Spinning"),
        ("Reward__Support_Fist_Of_Kalguur", "Support: Fist Of Kalguur"),
        ("Reward__Skill_Fragments_Of_The_Past", "Skill: Fragments Of The Past"),
        ("Reward__Skill_Frostflame_Nova", "Skill: Frostflame Nova"),
        ("Reward__1x_Gemcutter_s_Prism", "1x Gemcutter's Prism"),
        ("Reward__1x_Glacial_Rune", "1x Glacial Rune"),
        ("Reward__1x_Glassblower_s_Bauble", "1x Glassblower's Bauble"),
        ("Reward__1x_Greater_Adept_Rune", "1x Greater Adept Rune"),
        ("Reward__1x_Greater_Body_Rune", "1x Greater Body Rune"),
        ("Reward__1x_Greater_Chaos_Orb", "1x Greater Chaos Orb"),
        ("Reward__1x_Greater_Charging_Rune", "1x Greater Charging Rune"),
        ("Reward__1x_Greater_Desert_Rune", "1x Greater Desert Rune"),
        ("Reward__1x_Greater_Exalted_Orb", "1x Greater Exalted Orb"),
        ("Reward__1x_Greater_Glacial_Rune", "1x Greater Glacial Rune"),
        ("Reward__1x_Greater_Inspiration_Rune", "1x Greater Inspiration Rune"),
        ("Reward__1x_Greater_Iron_Rune", "1x Greater Iron Rune"),
        ("Reward__1x_Greater_Jeweller_s_Orb", "1x Greater Jeweller's Orb"),
        ("Reward__1x_Greater_Mind_Rune", "1x Greater Mind Rune"),
        ("Reward__1x_Greater_Orb_of_Augmentation", "1x Greater Orb of Augmentation"),
        ("Reward__1x_Greater_Orb_of_Transmutation", "1x Greater Orb of Transmutation"),
        ("Reward__1x_Greater_Rebirth_Rune", "1x Greater Rebirth Rune"),
        ("Reward__1x_Greater_Regal_Orb", "1x Greater Regal Orb"),
        ("Reward__1x_Greater_Resolve_Rune", "1x Greater Resolve Rune"),
        ("Reward__1x_Greater_Robust_Rune", "1x Greater Robust Rune"),
        ("Reward__1x_Greater_Stone_Rune", "1x Greater Stone Rune"),
        ("Reward__1x_Greater_Storm_Rune", "1x Greater Storm Rune"),
        ("Reward__1x_Greater_Vision_Rune", "1x Greater Vision Rune"),
        ("Reward__1x_Greater_Ward_Rune", "1x Greater Ward Rune"),
        ("Reward__Skill_Grim_Pillars", "Skill: Grim Pillars"),
        ("Reward__Support_Healing_Runes", "Support: Healing Runes"),
        ("Reward__1x_Hedgewitch_Assandra_s_Rune_of_Wisdom", "1x Hedgewitch Assandra's Rune of Wisdom"),
        ("Reward__1x_Hinekora_s_Lock", "1x Hinekora's Lock"),
        ("Reward__Skill_Hollow_Shell", "Skill: Hollow Shell"),
        ("Reward__1x_Inspiration_Rune", "1x Inspiration Rune"),
        ("Reward__1x_Ire_of_Aldur", "1x Ire of Aldur"),
        ("Reward__1x_Iron_Rune", "1x Iron Rune"),
        ("Reward__1x_Katla_s_Gloom", "1x Katla's Gloom"),
        ("Reward__1x_Kolr_s_Hunt", "1x Kolr's Hunt"),
        ("Reward__Krillson_s_Bay_Key", "Krillson's Bay Key"),
        ("Reward__1x_Lady_Hestra_s_Rune_of_Winter", "1x Lady Hestra's Rune of Winter"),
        ("Reward__1x_Lesser_Adept_Rune", "1x Lesser Adept Rune"),
        ("Reward__1x_Lesser_Body_Rune", "1x Lesser Body Rune"),
        ("Reward__1x_Lesser_Charging_Rune", "1x Lesser Charging Rune"),
        ("Reward__1x_Lesser_Desert_Rune", "1x Lesser Desert Rune"),
        ("Reward__1x_Lesser_Glacial_Rune", "1x Lesser Glacial Rune"),
        ("Reward__1x_Lesser_Inspiration_Rune", "1x Lesser Inspiration Rune"),
        ("Reward__1x_Lesser_Iron_Rune", "1x Lesser Iron Rune"),
        ("Reward__1x_Lesser_Jeweller_s_Orb", "1x Lesser Jeweller's Orb"),
        ("Reward__1x_Lesser_Mind_Rune", "1x Lesser Mind Rune"),
        ("Reward__1x_Lesser_Rebirth_Rune", "1x Lesser Rebirth Rune"),
        ("Reward__1x_Lesser_Resolve_Rune", "1x Lesser Resolve Rune"),
        ("Reward__1x_Lesser_Robust_Rune", "1x Lesser Robust Rune"),
        ("Reward__1x_Lesser_Stone_Rune", "1x Lesser Stone Rune"),
        ("Reward__1x_Lesser_Storm_Rune", "1x Lesser Storm Rune"),
        ("Reward__1x_Lesser_Vision_Rune", "1x Lesser Vision Rune"),
        ("Reward__1x_Lesser_Ward_Rune", "1x Lesser Ward Rune"),
        ("Reward__Skill_Leylines", "Skill: Leylines"),
        ("Reward__1x_Masterwork_Rune", "1x Masterwork Rune"),
        ("Reward__1x_Medved_s_Boon", "1x Medved's Boon"),
        ("Reward__1x_Medved_s_Saga", "1x Medved's Saga"),
        ("Reward__1x_Medved_s_Tending", "1x Medved's Tending"),
        ("Reward__1x_Mind_Rune", "1x Mind Rune"),
        ("Reward__1x_Mirror_of_Kalandra", "1x Mirror of Kalandra"),
        ("Reward__1x_Mystic_Alloy", "1x Mystic Alloy"),
        ("Reward__1x_Olroth_s_Boon", "1x Olroth's Boon"),
        ("Reward__1x_Olroth_s_Saga", "1x Olroth's Saga"),
        ("Reward__1x_Orb_of_Alchemy", "1x Orb of Alchemy"),
        ("Reward__1x_Orb_of_Annulment", "1x Orb of Annulment"),
        ("Reward__1x_Orb_of_Augmentation", "1x Orb of Augmentation"),
        ("Reward__1x_Orb_of_Chance", "1x Orb of Chance"),
        ("Reward__1x_Orb_of_Transmutation", "1x Orb of Transmutation"),
        ("Reward__1x_Passion_of_Aldur", "1x Passion of Aldur"),
        ("Reward__1x_Perfect_Chaos_Orb", "1x Perfect Chaos Orb"),
        ("Reward__1x_Perfect_Exalted_Orb", "1x Perfect Exalted Orb"),
        ("Reward__1x_Perfect_Flux", "1x Perfect Flux"),
        ("Reward__1x_Perfect_Jeweller_s_Orb", "1x Perfect Jeweller's Orb"),
        ("Reward__1x_Perfect_Orb_of_Augmentation", "1x Perfect Orb of Augmentation"),
        ("Reward__1x_Perfect_Orb_of_Transmutation", "1x Perfect Orb of Transmutation"),
        ("Reward__Skill_Powered_by_Verisium", "Skill: Powered by Verisium"),
        ("Reward__1x_Prismatic_Alloy", "1x Prismatic Alloy"),
        ("Reward__1x_Protective_Alloy", "1x Protective Alloy"),
        ("Reward__Rare_Unique_Item", "Rare Unique Item"),
        ("Reward__1x_Rebirth_Rune", "1x Rebirth Rune"),
        ("Reward__Skill_Refutation", "Skill: Refutation"),
        ("Reward__1x_Regal_Orb", "1x Regal Orb"),
        ("Reward__Skill_Remnants_of_Kalguur", "Skill: Remnants of Kalguur"),
        ("Reward__Skill_Repulsion", "Skill: Repulsion"),
        ("Reward__1x_Resolve_Rune", "1x Resolve Rune"),
        ("Reward__1x_Robust_Rune", "1x Robust Rune"),
        ("Reward__1x_Rune_of_Accumulation", "1x Rune of Accumulation"),
        ("Reward__1x_Rune_of_Acrobatics", "1x Rune of Acrobatics"),
        ("Reward__1x_Rune_of_Confrontation", "1x Rune of Confrontation"),
        ("Reward__1x_Rune_of_Consistency", "1x Rune of Consistency"),
        ("Reward__1x_Rune_of_Culmination", "1x Rune of Culmination"),
        ("Reward__1x_Rune_of_Foundations", "1x Rune of Foundations"),
        ("Reward__1x_Rune_of_Reach", "1x Rune of Reach"),
        ("Reward__1x_Rune_of_Renown", "1x Rune of Renown"),
        ("Reward__1x_Rune_of_the_Blossom", "1x Rune of the Blossom"),
        ("Reward__1x_Rune_of_the_Hunt", "1x Rune of the Hunt"),
        ("Reward__1x_Rune_of_the_Prism", "1x Rune of the Prism"),
        ("Reward__1x_Rune_of_Vital_Flame", "1x Rune of Vital Flame"),
        ("Reward__1x_Rune_of_Vitality", "1x Rune of Vitality"),
        ("Reward__Support_Runeforged_Blades", "Support: Runeforged Blades"),
        ("Reward__1x_Runic_Alloy", "1x Runic Alloy"),
        ("Reward__Support_Runic_Extraction", "Support: Runic Extraction"),
        ("Reward__Support_Runic_Infusion", "Support: Runic Infusion"),
        ("Reward__Skill_Runic_Reprieve", "Skill: Runic Reprieve"),
        ("Reward__1x_Saqawal_s_Rune_of_Erosion", "1x Saqawal's Rune of Erosion"),
        ("Reward__1x_Saqawal_s_Rune_of_Memory", "1x Saqawal's Rune of Memory"),
        ("Reward__1x_Saqawal_s_Rune_of_the_Sky", "1x Saqawal's Rune of the Sky"),
        ("Reward__Support_Scouring_Flame", "Support: Scouring Flame"),
        ("Reward__1x_Serle_s_Triumph", "1x Serle's Triumph"),
        ("Reward__Skill_Skyfall", "Skill: Skyfall"),
        ("Reward__1x_Sovereign_Alloy", "1x Sovereign Alloy"),
        ("Reward__1x_Stone_Rune", "1x Stone Rune"),
        ("Reward__1x_Storm_Rune", "1x Storm Rune"),
        ("Reward__1x_Thane_Girt_s_Rune_of_Wildness", "1x Thane Girt's Rune of Wildness"),
        ("Reward__1x_Thane_Grannell_s_Rune_of_Mastery", "1x Thane Grannell's Rune of Mastery"),
        ("Reward__1x_Thane_Leld_s_Rune_of_Spring", "1x Thane Leld's Rune of Spring"),
        ("Reward__1x_Thane_Myrk_s_Rune_of_Summer", "1x Thane Myrk's Rune of Summer"),
        ("Reward__1x_Thaumaturgic_Flux_Level_10", "1x Thaumaturgic Flux (Level 10)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_11", "1x Thaumaturgic Flux (Level 11)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_12", "1x Thaumaturgic Flux (Level 12)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_13", "1x Thaumaturgic Flux (Level 13)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_14", "1x Thaumaturgic Flux (Level 14)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_15", "1x Thaumaturgic Flux (Level 15)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_16", "1x Thaumaturgic Flux (Level 16)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_17", "1x Thaumaturgic Flux (Level 17)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_18", "1x Thaumaturgic Flux (Level 18)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_19", "1x Thaumaturgic Flux (Level 19)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_20", "1x Thaumaturgic Flux (Level 20)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_5", "1x Thaumaturgic Flux (Level 5)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_6", "1x Thaumaturgic Flux (Level 6)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_7", "1x Thaumaturgic Flux (Level 7)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_8", "1x Thaumaturgic Flux (Level 8)"),
        ("Reward__1x_Thaumaturgic_Flux_Level_9", "1x Thaumaturgic Flux (Level 9)"),
        ("Reward__1x_The_Greatwolf_s_Rune_of_Claws", "1x The Greatwolf's Rune of Claws"),
        ("Reward__1x_The_Greatwolf_s_Rune_of_Willpower", "1x The Greatwolf's Rune of Willpower"),
        ("Reward__1x_The_Runebinder_s_Alloy", "1x The Runebinder's Alloy"),
        ("Reward__1x_The_Runefather_s_Alloy", "1x The Runefather's Alloy"),
        ("Reward__1x_Thrud_s_Might", "1x Thrud's Might"),
        ("Reward__1x_Transcendent_Alloy", "1x Transcendent Alloy"),
        ("Reward__Skill_Triskelion_Cascade", "Skill: Triskelion Cascade"),
        ("Reward__1x_Uhtred_s_Boon", "1x Uhtred's Boon"),
        ("Reward__1x_Uhtred_s_Saga", "1x Uhtred's Saga"),
        ("Reward__1x_Uhtred_s_Sidereus", "1x Uhtred's Sidereus"),
        ("Reward__Uncut_Skill_Gem", "Uncut Skill Gem"),
        ("Reward__1x_Uncut_Skill_Gem_Level_19", "1x Uncut Skill Gem (Level 19)"),
        ("Reward__1x_Uncut_Skill_Gem_Level_20", "1x Uncut Skill Gem (Level 20)"),
        ("Reward__Uncut_Spirit_Gem", "Uncut Spirit Gem"),
        ("Reward__1x_Uncut_Spirit_Gem_Level_19", "1x Uncut Spirit Gem (Level 19)"),
        ("Reward__1x_Uncut_Spirit_Gem_Level_20", "1x Uncut Spirit Gem (Level 20)"),
        ("Reward__Uncut_Support_Gem", "Uncut Support Gem"),
        ("Reward__Skill_Verisium_Manifestations", "Skill: Verisium Manifestations"),
        ("Reward__Verisium_Pile", "Verisium Pile"),
        ("Reward__Very_Rare_Unique_item", "Very Rare Unique item"),
        ("Reward__1x_Vision_Rune", "1x Vision Rune"),
        ("Reward__1x_Void_Flux", "1x Void Flux"),
        ("Reward__Skill_Voltaic_Barrier", "Skill: Voltaic Barrier"),
        ("Reward__1x_Vorana_s_Boon", "1x Vorana's Boon"),
        ("Reward__1x_Vorana_s_Carnage", "1x Vorana's Carnage"),
        ("Reward__1x_Vorana_s_Saga", "1x Vorana's Saga"),
        ("Reward__1x_Ward_Rune", "1x Ward Rune"),
        ("Reward__Skill_Wardbound_Minions", "Skill: Wardbound Minions"),
        ("Reward__1x_Warding_Rune_of_Annihilation", "1x Warding Rune of Annihilation"),
        ("Reward__1x_Warding_Rune_of_Armature", "1x Warding Rune of Armature"),
        ("Reward__1x_Warding_Rune_of_Bodyguards", "1x Warding Rune of Bodyguards"),
        ("Reward__1x_Warding_Rune_of_Courage", "1x Warding Rune of Courage"),
        ("Reward__1x_Warding_Rune_of_Desperation", "1x Warding Rune of Desperation"),
        ("Reward__1x_Warding_Rune_of_Disintegration", "1x Warding Rune of Disintegration"),
        ("Reward__1x_Warding_Rune_of_Equinox", "1x Warding Rune of Equinox"),
        ("Reward__1x_Warding_Rune_of_Glancing", "1x Warding Rune of Glancing"),
        ("Reward__1x_Warding_Rune_of_Heart", "1x Warding Rune of Heart"),
        ("Reward__1x_Warding_Rune_of_Hollowing", "1x Warding Rune of Hollowing"),
        ("Reward__1x_Warding_Rune_of_Obsession", "1x Warding Rune of Obsession"),
        ("Reward__1x_Warding_Rune_of_Protection", "1x Warding Rune of Protection"),
        ("Reward__1x_Warding_Rune_of_Reinforcement", "1x Warding Rune of Reinforcement"),
        ("Reward__1x_Warding_Rune_of_Salvaging", "1x Warding Rune of Salvaging"),
        ("Reward__1x_Warding_Rune_of_Stability", "1x Warding Rune of Stability"),
        ("Reward__1x_Warding_Rune_of_Symbiosis", "1x Warding Rune of Symbiosis"),
        ("Reward__Unique_Amulet", "Unique Amulet"),
        ("Reward__Unique_Belt", "Unique Belt"),
        ("Reward__Unique_Body_Armour", "Unique Body Armour"),
        ("Reward__Unique_Boots", "Unique Boots"),
        ("Reward__Unique_Bow", "Unique Bow"),
        ("Reward__Unique_Crossbow", "Unique Crossbow"),
        ("Reward__Unique_Focus", "Unique Focus"),
        ("Reward__Unique_Gloves", "Unique Gloves"),
        ("Reward__Unique_Helmet", "Unique Helmet"),
        ("Reward__Unique_Jewellery", "Unique Jewellery"),
        ("Reward__Unique_One_Hand_Mace", "Unique One Hand Mace"),
        ("Reward__Unique_Quarterstaff", "Unique Quarterstaff"),
        ("Reward__Unique_Quiver", "Unique Quiver"),
        ("Reward__Unique_Ring", "Unique Ring"),
        ("Reward__Unique_Sceptre", "Unique Sceptre"),
        ("Reward__Unique_Shield", "Unique Shield"),
        ("Reward__Unique_Spear", "Unique Spear"),
        ("Reward__Unique_Staff", "Unique Staff"),
        ("Reward__Unique_Talisman", "Unique Talisman"),
        ("Reward__Unique_Two_Hand_Mace", "Unique Two Hand Mace"),
        ("Reward__Unique_Wand", "Unique Wand"),
    };
}
